#!/bin/sh

DIR_HOOKS="${OPENSHIFT_REPO_DIR}.openshift/action_hooks"

chmod +x "${DIR_HOOKS}/start"
chmod +x "${DIR_HOOKS}/stop"

# start backup file
#[ -f app-root/runtime/repo/.gitbucket/ ] && cp -r app-root/runtime/repo/.gitbucket/ /tmp && rm -r app-root/runtime/repo/.gitbucket && cp -r /tmp/.gitbucket/ app-root/runtime/repo/
# end backup file
